### ISSUE TITLE
Where to configure it?

### ISSUE THREAD

**Issue by sandesh-bhoir** [Eon-Labs/dynamo-light#11]
The documentation doesn't show where to do the configuration for the environmental variables declared. I just want to retrieve data from db, can you assist

**Comment by ChenLi0830** [comment]
@sandesh-bhoir I Apologize for the late reply. 

The environment variables are documented here [link](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html). To declare them, you just run the following in your shell/terminal
```
export AWS_ACCESS_KEY_ID="Your AWS Access Key ID"
export AWS_SECRET_ACCESS_KEY="Your AWS Secret Access Key"
export AWS_REGION="us-west-2"

# Then assume your script to access your dynamoDB is called `example.js`, run the following
node example.js
```

**Comment by ChenLi0830** [comment]
I am closing the issue for now since it's quite out dated, but feel free to reopen it if you have further questions.
